### ISSUE TITLE
Suggestion: add $OPTIONS environment variable

### ISSUE THREAD

**Issue by lkollenberger** [ventz/docker-bind#14]
It'd be awesome to have this feature, replicating the functionality of the `/etc/default/bind9` file in Debian/Ubuntu distros. It would be really useful for example for adding the `-4` argument to bind in IPv4 only deployments.

A way to do it would be adding `$OPTIONS` to the last line in `/entrypoint.sh`.

**UPDATE from ventz (complete)**: Added arbitrary parameter passing to the `named` daemon. Everything passed "at the end" will be directly passed to named.

For Ex:
```
docker run -it --rm  ventz/bind SOMETHING1 SOMETHING2
```

**Comment by ventz** [comment]
@lkollenberger Agreed.

Proposing doing it this way, since CMD is added to the ENTRYPOINT:

```
ARG OPTIONS
ENV OPTIONS ${OPTIONS}
...
COPY entrypoint.sh /
ENTRYPOINT ["/entrypoint.sh"] 
CMD ${OPTIONS}
```

Please test it out to see if it covers your scenario and let me know. If it works, I'll push it out.

**Comment by lkollenberger** [comment]
Hmm, I don't think passing the options as CMD is working, am I doing something wrong? This is my resulting `Dockerfile`:
```
FROM alpine:latest
EXPOSE 53 53/udp

RUN apk --update upgrade && apk add bind

# /etc/bind needs to be owned by root, group owned by "bind", and chmod 750
# since we are mounting, do it manually
# NOTE: Per Dockerfile manual --> need to mkdir the mounted dir to chown
# &
# /var/bind needs to be owned by root, group owned by "bind", and chmod 770
# since we are mounting, do it manually
# NOTE: Per Dockerfile manual --> need to mkdir the mounted dir to chown
# &
# Get latest bind.keys
RUN mkdir -m 0770 -p /etc/bind && chown -R root:named /etc/bind ; \
    mkdir -m 0770 -p /var/cache/bind && chown -R root:named /var/cache/bind ; \
    wget -q -O /etc/bind/bind.keys https://ftp.isc.org/isc/bind9/keys/9.11/bind.keys.v9_11 ; \
    rndc-confgen -a -r /dev/urandom

COPY configs/. /etc/bind/

# Mounts
# NOTE: Per Dockerfile manual -->
#       "if any build steps change the data within the volume
#        after it has been declared, those changes will be discarded."
VOLUME ["/etc/bind"]
VOLUME ["/var/cache/bind"]

ARG OPTIONS
ENV OPTIONS ${OPTIONS}

COPY entrypoint.sh /
ENTRYPOINT ["/entrypoint.sh"]
CMD ${OPTIONS}
```
As it is, it's doing nothing (the `$OPTIONS` variable doesn't get passed to bind). I think that's because the CMD is not getting passed to bind on the entrypoint, so I tried adding `"$@"` to the last line in that script. However, now bind doesn't even start, it's complaining about extra arguments:
```
root@crapserv:~# docker logs -f bind
usage: named [-4|-6] [-c conffile] [-d debuglevel] [-E engine] [-f|-g]
             [-n number_of_cpus] [-p port] [-s] [-S sockets] [-t chrootdir]
             [-u username] [-U listeners] [-m {usage|trace|record|size|mctx}]
usage: named [-v|-V]
```
Running a `docker inspect bind` shows this:
```
            "Env": [
                "OPTIONS=-4",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "${OPTIONS}"
            ],
            "ArgsEscaped": true,
            "WorkingDir": "",
            "Entrypoint": [
                "/entrypoint.sh"
            ],
```
So maybe the command line that runs `named` ends up like `exec /usr/sbin/named -c /etc/bind/named.conf -g -u named /bin/sh -c -4` which of course, is not valid.
Any ideas? For reference, this is my docker-compose:
```
version: "3"
services:
        bind:
                image: lkollenberger/bind:testing
                container_name: bind
                network_mode: host
                volumes:
                        - "/data/configs/bind/etc_bind:/etc/bind"
                        - "/data/configs/bind/var_cache_bind:/var/cache/bind"
                        - "/data/configs/bind/var_log_named:/var/log/named"
                environment:
                        - "OPTIONS=-4"
                restart: unless-stopped
```
Thanks!
